### ISSUE TITLE
Documentation Improvements - Expand recommended usage patterns

### ISSUE THREAD

**Issue by Peter554** [EnableSoftware/Enable.Extensions.Queuing#26]
It may be worth updating the README to expand more on recommended usage patterns.

For example, considering the case of azure service bus the [microsoft docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#reusing-factories-and-clients) say:

> It is recommended that you do not close messaging factories or queue, topic, and subscription clients after you send a message, and then re-create them when you send the next message. Closing a messaging factory deletes the connection to the Service Bus service, and a new connection is established when recreating the factory. Establishing a connection is an expensive operation that you can avoid by reusing the same factory and client objects for multiple operations. 

In terms of our library there are at least two sensible usage patterns:

```csharp
using (var queueClient = queueClientFactory.GetQueueReference("my-queue"))
{
    // Do stuff
}
```

and (once #20 and #21 is resolved)

```csharp
var queueClient = queueClientFactory.GetQueueReference("my-queue")

// Do stuff
```

It seems to me that in this case the microsoft docs are advertising the second option as being more efficient. Perhaps the README should at least mention the alternative usage pattern? Currently we are mainly using pattern 1 in our solutions - which is fine - but it may be more efficient in some cases to use pattern 2 and therefore we could try and raise awareness of this.

Also, for example, again looking at the microsoft docs above, in the case of azure service bus it is most efficient to inject the `QueueClientFactory` at the application level as a singleton. Obviously this isn't a requirement, but to get the best performance from our package it should be followed. Perhaps some usage advice relating to this should also be added?

**Comment by cgwrench** [comment]
Hi @Peter554. Thanks for the issue.

However, I don't agree that the second option is a "sensible pattern". Our queue clients implement `IDisposable`. We therefore should always wrap our usage of queue clients in a `using` block. I don't see how the linked issues change that at all.

Also, injecting the ueue client factories as singleton won't have an impact on performance. We're updating the queue clients to reuse connections, rather than create a new connection per instance of a queue client. This is a performance win that will be available "out of the box". No changes are required from end users to benefit from this.

**Comment by Peter554** [comment]
Thanks @cgwrench. 

Yes sorry I think I was wrong about the `QueueClientFactory` needing to be a singleton for optimal performance.

My interpretation of the [Microsoft docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#reusing-factories-and-clients) is still that the second pattern is both sensible and optimal in many cases. But perhaps I'm just wrong/misunderstanding things. Thanks anyway for considering it.
